ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging
ccflags-y += -Idrivers/gpu/drm/msm/sde
ccflags-y += -Idrivers/gpu/drm/msm/vivosrc

obj-y +=  \
	vivo_lcm_panel_common.o \
	vivo_lcm_smart_aod.o
